### PR TITLE
Update cameraManager.ts

### PR DESCRIPTION
**Pull request by rphlcristian**

### CODE REVIEW

**Comment by filfat** [comment]
What's the point of this change?

**Comment by rphlcristian** [comment]
Trying to strip the rotation on camera. (Sorry inglês)

**Comment by starcorroder** [comment]
True ... The camera is sideways which makes it lag more

**Comment by rphlcristian** [comment]
I will try to make another and last change

**Comment by starcorroder** [comment]
No ... It's not last ... There are many things missing ... Like 
1. Autofocus on touch
2. Screen cracks on start and then works

**Comment by filfat** [comment]
@starcorroder 
The "crack" is just simulated noise meant to show that we're initializing the camera, we could just switch it to pure black but that's boring :P

I'll close this PR as @Ahuge is currently working on this and a bunch of other cameraManager related stuff :)

**Comment by starcorroder** [comment]
Ohkay ... So your not only making a windows app ... But also upgrading the actual Snapchat from boring to fun 😂

**Pull request closed without merging**
