### PR TITLE
Adding rotation values to the camera manager

### PR DESCRIPTION
**Pull request by Ahuge**

### CODE REVIEW

**Comment by pvrs12** [comment]
These are upside down for me, which means this might need to change specifically per platform

**Comment by Ahuge** [comment]
ah shoot 
@pvrs12 What device are you on?

**Comment by pvrs12** [comment]
Lumia 640 running 10

**Comment by Ahuge** [comment]
Ok thanks.

**Comment by filfat** [comment]
Alright, I'll merge this and we'll figure out the rotation per platform-basis.

**Pull request merged**
