### PR TITLE
Add settings menu and logout button

### PR DESCRIPTION
**Pull request by pvrs12**
Adds the settings/index.html display when the settings button is tapped.
Adds Logout and Back buttons on the settings page (temporary)
Adds button which removes all the stored credentials from the vault

This is a PR for a temporary fix requested by https://www.reddit.com/r/swiftsnapper/comments/41k4p2/logout/. I know the project is in a holding pattern based on the Casper API, but this needn't change when the new API exists

### CODE REVIEW

**Comment by dreamilk34** [comment]
and works for all lumias?

**Comment by dreamilk34** [comment]
im from l830 and i can't logout, and can't enter in the definitions.

**Comment by pvrs12** [comment]
I have no reason to believe that it won't. I've tested it on my 640

**Comment by dreamilk34** [comment]
what build i need to download to see it?

**Comment by pvrs12** [comment]
https://ci.appveyor.com/project/filfat/swiftsnapper/build/0.1.150/artifacts

**Comment by dreamilk34** [comment]
and what file? the first?

**Comment by dreamilk34** [comment]
now I can see 😉 thank you

**Pull request merged**
